-- ============================================
-- QuizifAI — Add option_explanations field to questions
-- ============================================

ALTER TABLE public.questions
  ADD COLUMN IF NOT EXISTS option_explanations JSONB NULL;

COMMENT ON COLUMN public.questions.option_explanations IS
  'Optional JSON object mapping each answer option to a 1-sentence explanation of why it is correct or incorrect, generated by AI.';
